var username;
var myName = "Muhammad Milad Raza";
var message = "'"+"Hello World"+"'";
alert(message);
var name = prompt("Enter Your Name");
var age = prompt("Enter Your Age");
var skill = prompt("Enter Your Skill");
alert(name);
alert(age);
alert(skill);
var pizza = alert("PIZZA \nPIZZ \nPIZ \nPI \nP");
var email = "miladrazabhatti@gmail.com";
alert("my email address is " + email);
var book = "A smarter way to learn JavaScript";
alert("I am trying to learn from the book " + book);
document.write("Yah! I can write HTML content through JavaScript");
var design = "--------------------ಥﾟДﾟ●Дﾟಥ--------------------";
alert (design);